
# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"

# Real zshrc. Lives in ~/.config/zsh/ via ZDOTDIR.
# Sourced by the stub at ~/.zshrc.

export ENV_DIR="$HOME/environment"

# ───────── source order is explicit ─────────
source "$ZDOTDIR/environment.zsh"     # FIRST — sets PATH, EDITOR
source "$ZDOTDIR/tools.zsh"           # mise/starship/atuin/zoxide inits
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/git.zsh"

# OS-specific
case "$OSTYPE" in
  darwin*) [[ -f "$ZDOTDIR/os-darwin.zsh" ]] && source "$ZDOTDIR/os-darwin.zsh" ;;
  linux*)  [[ -f "$ZDOTDIR/os-linux.zsh"  ]] && source "$ZDOTDIR/os-linux.zsh"  ;;
esac

# Profile-specific (gated by marker files)
[[ -f "$HOME/.config/environment/profile-work" ]]     && [[ -f "$ZDOTDIR/profile-work.zsh" ]]     && source "$ZDOTDIR/profile-work.zsh"
[[ -f "$HOME/.config/environment/profile-personal" ]] && [[ -f "$ZDOTDIR/profile-personal.zsh" ]] && source "$ZDOTDIR/profile-personal.zsh"

# zsh plugins (git_clones in manifest.yaml; loader generated by generate.py)
[[ -f "$ENV_DIR/out/zsh-plugins.zsh" ]] && source "$ENV_DIR/out/zsh-plugins.zsh"

# Command-line keybindings (Cmd/Option arrows, word + line motions).
# MUST come after the plugin loader: zsh-autosuggestions and
# zsh-syntax-highlighting both wrap ZLE widgets as they load, so binding first
# would let them re-bind over the top. See the file header for why vi mode
# needs these spelled out.
source "$ZDOTDIR/keybindings.zsh"

# Local overlay (gitignored)
[[ -f "$ENV_DIR/local/zshrc.local" ]] && source "$ENV_DIR/local/zshrc.local"
[[ -f "$ENV_DIR/local/env.local" ]]   && source "$ENV_DIR/local/env.local"

# Kiro CLI shell integration — `post` half (WORK ONLY). Must be the LAST thing
# sourced, and paired with the `pre` half in profile-work.zsh. See that file
# for why pre/post are split. Work-marker-gated so it no-ops elsewhere.
if [[ -f "$HOME/.config/environment/profile-work" ]] && command -v kiro-cli >/dev/null 2>&1; then
  eval "$(kiro-cli init zsh post 2>/dev/null)"
fi


# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
